name: eBUSd
version: "0.82.rc2"
slug: ebusd
description: >
  This Add-on runs eBUSd, a daemon for handling communication with eBUS devices
  connected to a 2-wire bus system (“energy bus” used by numerous heating systems)
  You currently need an eBUS hardware interface connected via usb to make use of this addon
url: https://community.home-assistant.io/t/an-ebusd-add-on/344852
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: "system"
boot: "auto"
uart: true
ports:
  8888/tcp: 8888
  8889/tcp: 8889
ports_description:
  8888/tcp: eBUSd port
  8889/tcp: HTTP port
options:
  scanconfig: true
  foreground: true
schema:
  device_usb: "device(subsystem=tty)?"
  device_custom: "str?"
  latency: "int(0,10000)?"
  readonly: "bool?"
  foreground: "bool?"
  scanconfig: "bool?"
  logareas: "list(main|network|bus|update|all)?"
  loglevel: "list(error|notice|info|debug)?"
  mqtthost: "str?"
  mqttport: "int?"
  mqttuser: "str?"
  mqttpass: "str?"
  mqttjson: "bool?"
  mqttlog: "bool?"
  mqttretain: "bool?"
